### ISSUE TITLE
new release? 🤔

### ISSUE THREAD

**Issue by kloczek** [avahi/avahi#550] opened 2024-01-26 20:03 UTC
Looking on https://github.com/avahi/avahi/compare/v0.8...master I think that it would be good to release new version.
Any plans to do that soon? 🤔

**Comment by evverx** [comment] 2024-01-26 20:41
As far as I can remember @pemensik was planning to cut the next release. Given that rolling distros have been in sync with the master branch and I haven't seen any issues apart from https://gitlab.archlinux.org/archlinux/packaging/packages/avahi/-/issues/1 (which should be documented in the release notes) personally I think it should be fine to cut the release. https://github.com/avahi/avahi/issues/516 should be addressed one way or another though. I'll leave it to @pemensik to decide.

It's a duplicate of https://github.com/avahi/avahi/issues/503 though.

**Comment by pemensik** [comment] 2024-01-26 20:58
Let's close this and continue in #503 then.

**Closed by pemensik** 2024-01-26 20:58 UTC
Labels: duplicate, question

**Comment by Neustradamus** [comment] 2024-01-26 21:16
@kloczek: Thanks for your ticket, it shows that I am not alone ^^

Like @evverx and @pemensik have said, there is a ticket that I have done:
- https://github.com/avahi/avahi/issues/503

It is same for nss-dns, the latest is 0.15.1 (2021-06-12), there is a ticket:
- https://github.com/avahi/nss-mdns/releases
- https://github.com/avahi/nss-mdns/issues/85

**Comment by Neustradamus** [comment] 2024-01-26 21:27
@kloczek: Thanks for your ticket, it shows that I am not alone ^^

Like @evverx and @pemensik have said, there is a ticket that I have done:
- https://github.com/avahi/avahi/issues/503

It is same for nss-dns, the latest is 0.15.1 (2021-06-12), there is a ticket:
- https://github.com/avahi/nss-mdns/releases
- https://github.com/avahi/nss-mdns/issues/85

Note:

Previously, I have done this ticket:
- https://github.com/avahi/avahi/issues/325

And @ilkery has done one ticket too:
- https://github.com/avahi/avahi/issues/430
