### ISSUE TITLE
Attempting to use internal strlcpy with newer versions of glibc causes compiler error

### ISSUE THREAD

**Issue by jwillikers** [avahi/avahi#579] opened 2024-03-06 15:16 UTC
Newer versions of `glibc`, at least version 2.38, declare `strlcpy` in `/usr/include/strings.h`. Attempting to override Avahi's behavior to use the internal `strlcpy` with the configure option `ac_cv_func_strlcpy=no` results in the following compiler error in this situation.

```
/home/jordan/.conan2/p/b/avahi98352b3d5ad69/b/src/avahi-common/domain.c:482:15: error: static declaration of ‘strlcpy’ follows non-static declaration
  482 | static size_t strlcpy(char *dest, const char *src, size_t n) {
      |               ^~~~~~~
In file included from /home/jordan/.conan2/p/b/avahi98352b3d5ad69/b/src/avahi-common/domain.c:24:
/usr/include/string.h:506:15: note: previous declaration of ‘strlcpy’ with type ‘size_t(char * restrict,  const char * restrict,  size_t)’ {aka ‘long unsigned int(char * restrict,  const char * restrict,  long unsigned int)’}
  506 | extern size_t strlcpy (char *__restrict __dest,
      |               ^~~~~~~
```

The Conan package for Avahi implemented this workaround in conan-io/conan-center-index#20706, which describes the rational, i.e. keeping binary compatibility of the compiled libraries.

**Comment by evverx** [comment] 2024-03-06 16:04
Looking at https://github.com/conan-io/conan-center-index/pull/22996 it seems the plan is to rename `strlcpy` to `avahi_strlcpy` there.

Having read https://github.com/conan-io/conan-center-index/pull/20706 and https://github.com/conan-io/conan-center-index/pull/22996 I have to admit I'm not sure why `strlcpy` is detected by `configure` but `make` fails there. Are they run in two different environments?

**Comment by uilianries** [comment] 2024-03-07 08:40
@jwillikers Thank you for opening this discussion!

@evverx We are running the very same environment, and I can give some details in case you want to reproduce them:

- Currently we run GCC 5.4, 7, 9 and 11 (We past we had more)

Also, we use Docker images with these compiler in our CI, so you can reproduce the same environment in case you are interested.

```
docker run --rm -ti -v $PWD:/home/conan/project --platform=linux/amd64 conanio/gcc11-ubuntu16.04:2.1.0
# In the container
conan install -r conancenter --requires=avahi/0.8 --build=avahi
```

In case you don't want to use Conan, you still could use the same docker image to build manually, it's based on Ubuntu 16.04 (glibc 2.23) and has GCC 11.1.0 installed (we build from source). So you could install all dependencies via apt-get command. 


Other Docker linux images used in the CI:

- GCC 5.4.0: conanio/gcc5:latest (Based on Ubuntu 16.04 - glibc 2.23)
- GCC 7.2.0: conanio/gcc7:latest (Based on Ubuntu 17.10 - glibc 2.26)
- GCC 9.2.1: conanio/gcc9:latest (Based on Ubuntu 19.10 - glibc 2.30)

**Comment by evverx** [comment] 2024-03-07 09:54
I pulled the `conanio/gcc11-ubuntu16.04:2.1.0` image and ran `autogen.sh`, `configure` and `make` there manually. `strlcopy` wasn't detected there to judge from `config.log`:
```sh
configure:18987: checking for strlcpy
configure:18987: gcc -o conftest -g -O2 -std=c99 -Wall -W -Wextra -pedantic -pipe -Wformat -Wold-style-definition -Wdeclaration-after-statement -Wfloat-equal -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -fdiagnostics-show-option -Wno-cast-qual -fno-strict-aliasing   conftest.c  >&5
conftest.c:101:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
  101 | char strlcpy ();
      | ^~~~
conftest.c:110:1: warning: function declaration isn't a prototype [-Wstrict-prototypes]
  110 | main ()
      | ^~~~
conftest.c: In function 'main':
conftest.c:110:1: warning: old-style function definition [-Wold-style-definition]
/opt/conan/binutils/bin/ld: /tmp/cckVMyki.o: in function `main':
/home/conan/avahi/conftest.c:112: undefined reference to `strlcpy'
collect2: error: ld returned 1 exit status
...
configure:18987: result: no
``` 
`HAVE_STRLCPY` wasn't defined
```sh
$ grep HAVE_STRLCPY config.h
/* #undef HAVE_STRLCPY */
```
and `make` succeeded.

**Comment by uilianries** [comment] 2024-03-07 10:03
@evverx Correct, using that scenario this works fine because you are running with glibc 2.23.

The error reported by @jwillikers is using glibc 2.38, but we don't really have that version available in Conan.

@jwillikers Could you please share your environment, so we can reproduce your error as reported? Do you have a proper Docker image or something to make it easier to reproduce?

**Comment by evverx** [comment] 2024-03-07 10:06
I'm trying to figure out where https://github.com/conan-io/conan-center-index/pull/20706 comes from. As far as I understand `ac_cv_func_strlcpy=no` was added to fix it and the reason it fails with 2.38.

**Comment by uilianries** [comment] 2024-03-07 13:21
Okay, now I'm able to reproduce the original error, it happens only when liking to avahi as static library to a dummy application. The docker image is the same as the previous `conanio/gcc11-ubuntu16.04`.

Full build log using Conan, including config.log:

https://gist.github.com/uilianries/09ec284c4562d1c892911a5b2bea9587

The error was because `HAVE_STRLCPY` is 1 when building avahi/0.8, then using the implementation from avahi, but when linking, the application try to use from glibc instead, because glibc is linked dynamically.

**Comment by jwillikers** [comment] 2024-03-07 13:23
@uilianries Is the test package build directory cached or created new each time?

**Comment by evverx** [comment] 2024-03-07 15:03
> using the implementation from avahi

I'm not sure it was used there. Looking at
```c
/home/conan/.conan2/p/b/avahib743c718c6fca/b/src/avahi-common/domain.c:527:17: warning: implicit declaration of function 'strlcpy'; did you mean 'strncpy'? [-Wimplicit-function-declaration]
  527 |                 strlcpy(name, buf, name_size);
      |                 ^~~~~~~
      |                 strncpy
```
`configure` apparently detected it, set `HAVE_STRLCPY` to 1 and then the compiler failed to see `strlcpy`. That's weird.

**Comment by evverx** [comment] 2024-03-07 15:23
Would it be possible to pass `V=1` to `make` somehow to take a look at the full command line and compare it with what `configure` sees?

**Comment by evverx** [comment] 2024-03-07 16:07
Here's what I saw when I ran `conan create all --version=0.8 -o "*/*:shared=False"` in that container:
```sh
avahi/0.8 (test package): Running CMake.build()
avahi/0.8 (test package): RUN: cmake --build "/home/conan/conan-center-index/recipes/avahi/all/test_package/build/gcc-11-x86_64-gnu17-release" -- -j2
Scanning dependencies of target test_package
[ 50%] Building C object CMakeFiles/test_package.dir/test_package.c.o
[100%] Linking C executable test_package
[100%] Built target test_package


======== Testing the package: Executing test ========
avahi/0.8 (test package): Running test()
avahi/0.8 (test package): RUN: ./test_package
*** WARNING *** The program 'test_package' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
DNSServiceBrowse failed: -65537
```
I can't reproduce it.

**Comment by uilianries** [comment] 2024-03-07 16:41
> Would it be possible to pass `V=1` to `make` somehow to take a look at the full command line and compare it with what `configure` sees?

Yes, let me do it now and I'll post the results.

**Comment by evverx** [comment] 2024-03-07 16:51
FWIW I have no idea how conan works. It would be ideal if it was possible to paste the exact `configure` and `make` commands (along with the environment variables and so on) I need to run in that container without conan to trigger that issue. As far as I can tell either the autodetection logic is broken or the build environment changes somehow between `configure` and `make`.

**Comment by uilianries** [comment] 2024-03-07 17:09
@evverx No problem, Conan should not poison the poison, it runs the command lines, but they are printed as well, so we are capable to reproduce all step. The only different are the dependencies, because using Conan we will have them installed from a separated server, not from apt. 

The build with make V1 is here: https://gist.github.com/uilianries/579a8e65f8f52bf9d90e5bc6978debb7

To clarify the steps, we don't run `autogen.sh`, but only configure and make. We are using the release package https://github.com/lathiat/avahi/releases/download/v0.8/avahi-0.8.tar.gz to build only, no patches involved.

The configure and make like listed in the log are:

```
configure --disable-shared --enable-static --prefix=/ '--bindir=${prefix}/bin' '--sbindir=${prefix}/bin' '--libdir=${prefix}/lib' '--includedir=${prefix}/include' '--oldincludedir=${prefix}/include' --enable-compat-libdns_sd --disable-gtk3 --disable-mono --disable-monodoc --disable-python --disable-qt5 --with-systemdsystemunitdir=/lib/systemd/system ac_cv_func_setproctitle=no 

...

make V=1 -j10
```

Note that we set `ac_cv_func_setproctitle=no`. IIRC is related to the ancient glibc and because we are not running FreeBSD.

**Comment by evverx** [comment] 2024-03-07 18:29
The commands are huge:
```
configure:18977: checking for strlcpy
configure:18977: gcc -o conftest  -m64 -fPIC -O3 -fstack-protector -std=c99 -Wall -W -Wextra -pedantic -pipe -Wformat -Wold-style-definition -Wdeclaration-after-statement -Wfloat-equal -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -fdiagnostics-show-option -Wno-cast-qual -fno-strict-aliasing  -DNDEBUG -I/home/conan/.conan2/p/glib916daa5e743b2/p/include/gio-unix-2.0 -I/home/conan/.conan2/p/glib916daa5e743b2/p/include -I/home/conan/.conan2/p/glib916daa5e743b2/p/include/glib-2.0 -I/home/conan/.conan2/p/glib916daa5e743b2/p/lib/glib-2.0/include -I/home/conan/.conan2/p/libev1ea723d423310/p/include -I/home/conan/.conan2/p/libse54dfebcbdb892/p/include -I/home/conan/.conan2/p/opens6bc5acb1d2d1b/p/include -I/home/conan/.conan2/p/dbusf1e74faa737b6/p/include -I/home/conan/.conan2/p/dbusf1e74faa737b6/p/include/dbus-1.0 -I/home/conan/.conan2/p/dbusf1e74faa737b6/p/lib/dbus-1.0/include -I/home/conan/.conan2/p/pcre2d184a55a6d726/p/include -I/home/conan/.conan2/p/zlibcdd5270f9ab9f/p/include -I/home/conan/.conan2/p/gdbm7be2239273722/p/include -I/home/conan/.conan2/p/expat3ece0af824d2f/p/include -I/home/conan/.conan2/p/libda9828781edb74a/p/include -I/home/conan/.conan2/p/bzip24ed69d4fecc16/p/include -I/home/conan/.conan2/p/libmo527270335910e/p/include -I/home/conan/.conan2/p/libmo527270335910e/p/include/libmount -I/home/conan/.conan2/p/libel6d8681f2e3617/p/include -I/home/conan/.conan2/p/libel6d8681f2e3617/p/include/libelf -I/home/conan/.conan2/p/libfff66040185d3f0/p/include -DDBUS_STATIC_BUILD -DPCRE2_STATIC -DXML_STATIC -DFFI_BUILDING  -m64 -Wl,--export-dynamic -L/home/conan/.conan2/p/glib916daa5e743b2/p/lib -L/home/conan/.conan2/p/libev1ea723d423310/p/lib -L/home/conan/.conan2/p/libse54dfebcbdb892/p/lib -L/home/conan/.conan2/p/opens6bc5acb1d2d1b/p/lib -L/home/conan/.conan2/p/dbusf1e74faa737b6/p/lib -L/home/conan/.conan2/p/pcre2d184a55a6d726/p/lib -L/home/conan/.conan2/p/zlibcdd5270f9ab9f/p/lib -L/home/conan/.conan2/p/gdbm7be2239273722/p/lib -L/home/conan/.conan2/p/expat3ece0af824d2f/p/lib -L/home/conan/.conan2/p/libda9828781edb74a/p/lib -L/home/conan/.conan2/p/bzip24ed69d4fecc16/p/lib -L/home/conan/.conan2/p/libmo527270335910e/p/lib -L/home/conan/.conan2/p/libel6d8681f2e3617/p/lib -L/home/conan/.conan2/p/libfff66040185d3f0/p/lib conftest.c  -lgio-2.0 -lgthread-2.0 -lgobject-2.0 -lgmodule-2.0 -lglib-2.0 -levent_pthreads -levent_openssl -levent_extra -levent_core -lselinux -lsepol -lssl -lcrypto -ldbus-1 -lpcre2-32 -lpcre2-16 -lpcre2-posix -lpcre2-8 -lz -lgdbm -lexpat -ldaemon -lbz2 -lmount -lblkid -lelf -lffi -ldl -lresolv -lpthread -lrt -lm -lssp >&5
```
```
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/home/conan/.conan2/p/b/avahi560828b409f64/b/src/avahi-common -I..   -DNDEBUG -I/home/conan/.conan2/p/glib916daa5e743b2/p/include/gio-unix-2.0 -I/home/conan/.conan2/p/glib916daa5e743b2/p/include -I/home/conan/.conan2/p/glib916daa5e743b2/p/include/glib-2.0 -I/home/conan/.conan2/p/glib916daa5e743b2/p/lib/glib-2.0/include -I/home/conan/.conan2/p/libev1ea723d423310/p/include -I/home/conan/.conan2/p/libse54dfebcbdb892/p/include -I/home/conan/.conan2/p/opens6bc5acb1d2d1b/p/include -I/home/conan/.conan2/p/dbusf1e74faa737b6/p/include -I/home/conan/.conan2/p/dbusf1e74faa737b6/p/include/dbus-1.0 -I/home/conan/.conan2/p/dbusf1e74faa737b6/p/lib/dbus-1.0/include -I/home/conan/.conan2/p/pcre2d184a55a6d726/p/include -I/home/conan/.conan2/p/zlibcdd5270f9ab9f/p/include -I/home/conan/.conan2/p/gdbm7be2239273722/p/include -I/home/conan/.conan2/p/expat3ece0af824d2f/p/include -I/home/conan/.conan2/p/libda9828781edb74a/p/include -I/home/conan/.conan2/p/bzip24ed69d4fecc16/p/include -I/home/conan/.conan2/p/libmo527270335910e/p/include -I/home/conan/.conan2/p/libmo527270335910e/p/include/libmount -I/home/conan/.conan2/p/libel6d8681f2e3617/p/include -I/home/conan/.conan2/p/libel6d8681f2e3617/p/include/libelf -I/home/conan/.conan2/p/libfff66040185d3f0/p/include -DDBUS_STATIC_BUILD -DPCRE2_STATIC -DXML_STATIC -DFFI_BUILDING -I/home/conan/.conan2/p/b/avahi560828b409f64/b/src '-DDEBUG_TRAP=__asm__("int $3")'  -DAVAHI_LOCALEDIR=\"///locale\" -m64 -fPIC -O3 -fstack-protector -std=c99 -Wall -W -Wextra -pedantic -pipe -Wformat -Wold-style-definition -Wdeclaration-after-statement -Wfloat-equal -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wredundant-decls -Wmissing-noreturn -Wshadow -Wendif-labels -Wpointer-arith -Wbad-function-cast -Wcast-qual -Wcast-align -Wwrite-strings -fdiagnostics-show-option -Wno-cast-qual -fno-strict-aliasing -MT libavahi_common_la-domain.lo -MD -MP -MF .deps/libavahi_common_la-domain.Tpo -c -o libavahi_common_la-domain.lo `test -f 'domain.c' || echo '/home/conan/.conan2/p/b/avahi560828b409f64/b/src/avahi-common/'`domain.c
```
and I have to admit I'm not sure how to even start to untangle all those `-I`s and `-L`s to figure out where `strlcpy` disappears.

I think if it's a pressing issue it would probably make sense to get it around in https://github.com/conan-io/conan-center-index/pull/22996 for the time being and keep this issue open until it's tracked down to either the avahi build system or the conan build environment.

(On an unrelated note I noticed `-DNDEBUG` and I think it would be better not to pass it when avahi is built because historically asserts have been used to catch runtime errors too and without them things like https://github.com/avahi/avahi/issues/455 turn into memory corruptions)

**Comment by uilianries** [comment] 2024-03-07 19:19
@evverx I really appreciate your support! Thank you for checking it. Indeed is not a regular case.

So we will keep with the current patch in the issue https://github.com/conan-io/conan-center-index/pull/22996. For now, it look okay to avoid name conflict. In the future, when we update our base to use a newer glibc version, it will not be a problem anymore.

**Comment by evverx** [comment] 2024-12-11 07:47
It doesn't look like this issue is hit very often so I'll go ahead and close it.

(It can be a bug in the avahi build system of course so if anyone can track it down and pinpoint it it can always be reopened)

**Closed by evverx** 2024-12-11 07:47 UTC
Labels: build-system
