### ISSUE TITLE
Additional labels only permitted for direct mappings to an IP?

### ISSUE THREAD

**Issue by polarathene** [avahi/avahi#302] opened 2020-08-29 07:00 UTC
`/etc/nsswitch.conf` can have NSS forward a query to Avahi over mDNS based on a two-label heuristic, but when not using a `_minimal` variant in the config, such as `mdns4`, an additional configuration file `/etc/mdns.allow` permits additional labels to the left of the hostname.

Avahi itself allows for publishing such FQDNs such as `test.hostname.local` via `avahi-publish`(which can also use `-R` for mapping to an existing registered IP address) or `/etc/avahi/hosts` entries (which cannot map to an IP address already mapped to an FQDN for mDNS by Avahi). You cannot configure `/etc/avahi/avahi-daemon.conf` to leverage a `host-name` or `domain-name` with a `.` due to it introducing multi-label FQDN. 

The `avahi-publish` and `/etc/avahi/hosts` approaches do not appear to be discoverable (eg `avahi-browse -a`), possibly because they go against spec? They can of course be reached via `avahi-resolve` or `getent hosts --service=mdns4 test.hostname.local` (provided the `/etc/mdns.allow` enables the resolution, likewise for anything else that'd use `mdns4` if configured for NSS in `/etc/nsswitch.conf`, in which case the `--service=mdns4` can be ignored if querying with `getent hosts`).

There is no way to resolve to a hostname as an alias without such being defined explicitly. I've not been able to find any way that Avahi can be configured to support such a wildcard approach to resolving to the hostname, which I can't say would seem to be against expected behaviour to support or cause any conflict with mDNS resolution? Other clients may rightfully be restricted to mDNS queries like `mdns_minimal` enforces, but that's unrelated to Avahi (which is allowing such FQDNs to be supported and responded to otherwise), and why `nss-mdns` allows for the configuration to deviate when deemed appropriate by the system admin.

I have read reports of this from years ago, prior to the 0.11 release of `nss-mdns` in 2018, before macOS heuristics were added after the 0.10 `nss-mdns` release back in... 2007? What wasn't clear was if before those queries were forwarded to Avahi/mDNS, if the additional labels were being aliased to a hostname (eg `test.hostname.local` queried over mDNS as `hostname.local` instead) or explicitly published to specific IP addresses prior.

As it appears within the context of Avahi at least, that these additional labels are somewhat supported and can map to the same IP address (via `avahi-publish -R` or D-Bus API), I assume there was no magic/unexpected label truncation ever happening with `nss-mdns`, and these FQDNs were explicitly defined/published elsewhere, such as with Avahi.

---

Would wildcard resolution to a hostname be reasonable or difficult to support with Avahi?

It'd be useful for a reverse-proxy setup vs these additional labels being specified as `hostname.local` variants only, just publishing the hostname for the system itself?

I presently have CoreDNS configured with an external mdns plugin that OpenShift maintains. It supports Android which still doesn't support making mDNS queries via apps not explicitly configured for it by the developer, such as Chrome. Likewise, most clients would perform a unicast query instead of multicast when additional labels are involved, so this approach is able to catch those and proxy them to mDNS. Although, at least with the CoreDNS plugin(there's similar for Unbound, though I've not tried it), it seems to only support forwarding to mDNS when the address is discoverable (`avahi-browse -a`).

I am able to explicitly rewrite the DNS query `QUESTION SECTION` to the intended `hostname.local` for sending to mDNS/Avahi to respond to, and then have both `QUESTION` and `ANSWER` sections in the DNS response use the FQDN of the DNS request, so there is no mismatch against the FQDN response from mDNS(eg, `test.hostname.local` is received by CoreDNS, it is rewritten to query mDNS as `hostname.local`, then the response to return to the client is rewritten to `test.hostname.local` again), as this is required for certain clients to accept as legitimate and not a MITM attack (eg web browsers seem to reject the response otherwise). 

Presently this approach doesn't work well with CoreDNS for a dynamic wildcard request handling, as it's [`rewrite` plugin lacks having access to the original FQDN when rewriting the `ANSWER SECTION`](https://github.com/coredns/coredns/issues/2389#issuecomment-683241728).

---

## Summary

It would be nice if either was supported:

- Wildcard support option to respond to any `*.hostname.local` as `hostname.local` IP address.
- Some way to specify multiple hostnames or alias labels (`alias.hostname.local` / `alias-hostname.local`) more easily for the same IP address without `avahi-publish` or third-party scripts to use D-Bus API. Someone has asked for this within `/etc/avahi/avahi-daemon.conf` via a new field that would be similar to `browse-domains` but provide hostname aliasing instead.

**Comment by evverx** [comment] 2024-02-15 11:45
> Wildcard support option to respond to any *.hostname.local as hostname.local IP address

avahi has to make sure that A and AAAA resource records are unique so before replying to queries it has to send probe queries and announcements: https://datatracker.ietf.org/doc/html/rfc6762#section-8. I'm sorry but it can't just start synthesizing A and AAAA resource records on the fly.

> Some way to specify multiple hostnames or alias labels (alias.hostname.local / alias-hostname.local) more easily

It's a duplicate of https://github.com/avahi/avahi/issues/40.

**Closed by evverx** 2024-02-15 11:45 UTC
