### ISSUE TITLE
Chromecast groups not detected on Android clients when using Avahi to repeat accross subnets

### ISSUE THREAD

**Issue by B0ycee** [avahi/avahi#327] opened 2021-03-08 23:45 UTC
When using Avahi to repeat accross subnets, Chromecast groups are not visbile on Android devices.

[Detailed scenario]

Routing device (in this specific case pfsense 2.4.4/2.4.5 with Avahi 0.7 or 0.8) with connection to both Subnet A (i.e 192.168.1.0/24) and Subnet B (i.e 192.168.2.0/24).  Avahi configured to repeat between subnets/interfaces.

Two chromecast devices are connected to subnet A and are also configured as members of a Chromecast group named "BothChromecasts".

An Android device is connected to subnet B and is searching for Chromecast devices (for example user is searching in the Spotify app).

[Outcome]

Only the Chromecast devices will be shown, but the Chromecast group will be missing from Android device

However, using Chrome browser on a Windows device in subnet B will correctly show and operate as expected (2 Chromecasts and Chromecast group), therefore announcement does not appear entirely missing.

[Expected Outcome]

If Android device is directly connected to subnet A, Chromecast groups are shown and usable on Android device, therefore it would be expected this should also be the case with Avahi repeating between subnets.

[Workaround]

If Avahi is replaced with mdns-repeater (https://github.com/kennylevinsen/mdns-repeater/) between the subnets, issue is "resolved" and Chromecast groups are shown and usable on Android device.

My assumption is that there is something slightly different with the messaging after passing through Avahi which the Android clients do not like but the Windows Chrome clients tollerate.  Perhaps mdns-repeater repeats the packets more verbatim and therefore does not introduce the issue?

**Comment by B0ycee** [comment] 2023-08-30 21:00
Just to update its the same symptoms Avahi 0.8.1.  Chromecast devices are fine everywhere, but Chromecast speaker groups only show on Desktop Chrome Browser (and not on Android devices) in the repeated subnets.  mdns-Repeater "solves" the problem.

**Comment by evverx** [comment] 2023-11-07 19:57
I think it can be closed. I'm not sure the issue is actionable in its current form. My guess would be that it either has something to do with the malformed packets or, maybe, https://github.com/lathiat/avahi/issues/495.

**Comment by B0ycee** [comment] 2023-11-07 20:39
Don't understand how a bug can be closed as completed that hasn't been resolved?  Very odd.

Best it's left open so others are aware of the issue/limitation and workaround.

I can also try to provide some captures when I have time.

**Comment by evverx** [comment] 2023-11-07 20:47
> Don't understand how a bug can be closed as completed that hasn't been resolved?

I closed it because there isn't anything I can do to deduce what the issue is. If there had been configs/logs/pcaps and so on showing where packets get lost I hadn't closed it. Is it reproducible with the master branch of avahi?

**Comment by evverx** [comment] 2023-11-07 21:14
If it's https://github.com/lathiat/avahi/issues/379 it would be great if it was possible to apply the patch from https://github.com/lathiat/avahi/issues/379#issuecomment-1197439401 to see whether it helps.

**Comment by evverx** [comment] 2023-11-07 22:45
Just to clarify that patch is a kludge. It just prevent avahi from reflecting NSEC RRs. The idea is to figure out whether malformed NSEC RRs produced by avahi cause this issue. If they are it's a duplicate of https://github.com/lathiat/avahi/issues/379.

**Comment by evverx** [comment] 2024-10-09 12:28
I'll go ahead and close this. If this issue is still reproducible could you please open a new issue and fill out the issue form?

Either way I'm sure it's https://github.com/avahi/avahi/issues/379.

**Closed by evverx** 2024-10-09 12:28 UTC
Labels: needs-reporter-feedback, reflector
