### ISSUE TITLE
avahi fails to compile with "cannot stat 'service-types.db.coming': No such file or directory"

### ISSUE THREAD

**Issue by 2011** [avahi/avahi#604] opened 2024-05-29 09:41 UTC
Trying to compile the 0.8 tarball. I already ran into the missing build-db file (bug #277 and bug #298), and downloaded the file and placed it in the service-type-database/ directory. However, the compilation still fails with the following error messages:

```
make[2]: Leaving directory '/tmp/avahi-0.8/tests'
Making all in service-type-database
make[2]: Entering directory '/tmp/avahi-0.8/service-type-database'
  GEN      service-types.db
mv: cannot stat 'service-types.db.coming': No such file or directory
make[2]: *** [Makefile:666: service-types.db] Error 1
make[2]: Leaving directory '/tmp/avahi-0.8/service-type-database'
make[1]: *** [Makefile:825: all-recursive] Error 1
make[1]: Leaving directory '/tmp/avahi-0.8'
make: *** [Makefile:735: all] Error 2
```

And just for reference:

```
$ ls -al service-type-database/
total 132
drwxrwxr-x 1 user user    264 2024-05-29 09:28:52 ./
drwxrwxr-x 1 user user   1726 2024-05-29 09:27:39 ../
-rw-r--r-- 1 user user  21372 2024-05-29 09:27:37 Makefile
-rw-r--r-- 1 user user   1513 2018-09-14 05:31:28 Makefile.am
-rw-rw-r-- 1 user user  21385 2020-02-18 07:03:17 Makefile.in
-rwxrwxr-x 1 user user   1214 2024-01-30 17:16:03 build-db*
-rw-r--r-- 1 user user   5327 2020-02-17 03:41:02 service-types
-rw-r--r-- 1 user user   3123 2024-05-29 09:28:52 service-types.db.coming.bak
-rw-r--r-- 1 user user  54283 2024-05-29 09:28:52 service-types.db.coming.dat
-rw-r--r-- 1 user user   3123 2024-05-29 09:28:52 service-types.db.coming.dir
```

Any ideas on how to get this to compile?

**Comment by evverx** [comment] 2024-05-29 16:37
Could you try to clone the avahi repository, run `bootstrap.sh` and then `configure` to see if it compiles with the master branch? If it compiles could you create a tarball with `make dist`, unpack it and then run `configure` there to see if tarballs from the master branch work?

**Comment by gl-yziquel** [comment] 2024-06-08 16:59
@evverx

I cloned from .git, did ./bootstrap.sh, ./configure, and make, and got that exact same error.

**Comment by evverx** [comment] 2024-06-08 17:07
Could you provide more details? What distribution was it? How were the build dependencies installed?

**Comment by gl-yziquel** [comment] 2024-06-08 17:15
@evverx 

I'm on ubuntu. Mostly customised with lots of stuff built from source. Mantic. I got that build issue from git HEAD.

Not sure what details you'd really like.

**Comment by evverx** [comment] 2024-06-08 17:19
> Not sure what details you'd really like.

I'm trying to figure out how to recreate the build environment where it can be reproduced reliably.

(avahi is built on Ubuntu regularly on the CI and it has never happened there)

**Comment by gl-yziquel** [comment] 2024-06-08 17:56
The build environment where you'd have the most chance of reproducing it is a minimalistic mantic distribution. no X. Then build from git with ./boostrap.sh, ./configure and make. Install only the minimum apt dependencies that crop up when the previous instructions fail (for mono and monodoc, for instance).

It's possible that the full set of dependencies with the debian build system has some behaviour that is not checked in the ./configure phase and that makes my build fail.

I'm trying to do custom builds here, to get to know the software. I use ubuntu packages, and avahi is fine when packaged. It's just when trying to build from source "for fun" that it fails in the way described here.

I am **NOT** following ubuntu's packaging system. I'm trying to create my custom builds for my own ends, learning mostly. Which is why I believe we are talking accross one another: I am not complaining about ubuntu packaging or setup. But about the build instructions in the repo that, when followed "naively", lead to this result. This is NOT a debian / ubuntu packaging issue.

**Comment by evverx** [comment] 2024-06-08 18:02
I'm not saying it's a debian/ubuntu packaging issue. I'm trying to figure out what exactly I have to run to get it to fail. I've just launched an Ubuntu Mantic container and couldn't reproduce the issue there either. Could you provide the commands you ran to install the build dependencies?

**Comment by gl-yziquel** [comment] 2024-06-08 18:14
> I'm not saying it's a debian/ubuntu packaging issue. I'm trying to figure out what exactly I have to run to get it to fail. I've just launched an Ubuntu Mantic container and couldn't reproduce the issue there either. Could you provide the commands you ran to install the build dependencies?

No. Because I did not use ubuntu build dependencies.

Again. I build from source. Which means I also build my dependencies from source too... Including mono and such. My system is heavily customised. Which is why I believe this is a ./configure issue where it should fail for some reason but does not for some other even more mysterious reason.

The only way for me to provide you with a reproducible setup would be by attempting to set up a Dockerfile.

Otherwise, the best I can do is 1. Mantic 2. Very minimalistic setup of mantic. 3. clone git HEAD 0cf01ca49ad90008a2ad28855d92f02d15d634d5 4. run ./bootstrap, ./configure, make from dash shell 5. troubleshoot any missing install from 5 by building it from source too (or installing ubuntu package if rebuilding mono and monodoc is too much of a pain).

The issue I raised is the first that is not explicitly one about a missing dependency. (Though it could be a missing dependency undetected by ./configure, like one I had yesterday when building guix from source w/r to an internationalisation dependency).

I am trying to set up my own custom build system, here. There is no way to reproduce it short of asking me questions 1 by 1.

**Comment by evverx** [comment] 2024-06-08 18:27
> I believe this is a ./configure issue where it should fail for some reason but does not for some other even more mysterious reason

It can be a configure issue but as far as I understand it happens in custom build environments (otherwise it would be reported much more often probably) so if anyone can figure out what's going on patches are welcome.

**Comment by gl-yziquel** [comment] 2024-06-08 18:30
> > I believe this is a ./configure issue where it should fail for some reason but does not for some other even more mysterious reason
> 
> It can be a configure issue but as far as I understand it happens in custom build environments (otherwise it would be reported much more often probably) so if anyone can figure out what's going on patches are welcome.

Well, if you have context about what service-types.db.coming is and how it is handled, it may speed up my investigations.

**Comment by evverx** [comment] 2024-06-08 18:34
It's in service-type-database/Makefile.am:
https://github.com/avahi/avahi/blob/0cf01ca49ad90008a2ad28855d92f02d15d634d5/service-type-database/Makefile.am#L30-L32

**Comment by gl-yziquel** [comment] 2024-06-08 18:58
Thank you.

**Comment by evverx** [comment] 2024-06-18 16:43
@gl-yziquel I've been thinking about this and since it's the Python stuff could it be that there are several python instances/virtual environments (or something like that) in the build environment? It could probably explain why it can go sideways somewhere when, say, certain modules are installed system-wide but at some point another instance of python is run without those modules. I'm guessing but it's the only guess I have.

**Comment by gl-yziquel** [comment] 2024-06-18 21:37
> @gl-yziquel I've been thinking about this and since it's the Python stuff could it be that there are several python instances/virtual environments (or something like that) in the build environment? It could probably explain why it can go sideways somewhere when, say, certain modules are installed system-wide but at some point another instance of python is run without those modules. I'm guessing but it's the only guess I have.

Possible. I've moved on to other stuff, though. When that build / packaging issue pops up again, I'll have a look.

**Comment by evverx** [comment] 2024-12-11 05:49
Looks like this issue isn't hit very often and it's unclear how to reproduce it reliably so I'll go ahead and close it.

The error indicates that `build-db` did work but wasn't able to create that `coming` file. It can be a build system bug but I'm afraid I can't say how it can happen and what should/can be changed. If anyone can track it down and pinpoint it it can always be reopened.

**Closed by evverx** 2024-12-11 05:49 UTC
Labels: needs-reporter-feedback, build-system
